[project]
name = "mcp-client-example-langchain"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "mcp_proxy_for_aws",
    "langchain",
    "langchain-aws",
    "langchain-mcp-adapters",
]